# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Create Docker Image
          command: |
            export TAG=v1.1.${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=vinci
            docker build -t andycowley/$IMAGE_NAME:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            docker push andycowley/$IMAGE_NAME:$TAG
workflows:
  version: 2
  workflow:
    jobs:
    - build
